config/routes.rb
Rails.application.routes.draw do
  get 'signout', to: 'authentications#destroy', as: 'signout'
  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }
  resources :candidates
  resources :interview_appointments
  root to: 'candidates#index'

end

app/models/interview_appointment.rb
class InterviewAppointment < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable
    def self.connect_to_linkedin(auth, signed_in_resource=nil)
	    user = User.where(:provider => auth.provider, :uid => auth.uid).first
	    if user
	      return user
	    else
	      registered_user = User.where(:email => auth.info.email).first
	      if registered_user
	        return registered_user
	      else
	        user = User.create( first_name: auth.info.first_name,
	        					last_name: auth.info.last_name,
	        					headline: auth.info.description,
	                            provider: auth.provider,
	                            email: auth.info.email,
	                            password: Devise.friendly_token[0,20],
	                            summary: auth.extra.raw_info.summary,
	                            public_profile_url: auth.extra.raw_info.publicProfileUrl
	                          )
	      end

	    end
  	end   
 
 
	def disconnect_from_linkedin!
	  self.provider = nil
	  self.uid = nil
	  self.user_linkedin_connection = nil
	  self.save!
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	# Prevent CSRF attacks by raising an exception.
	# For APIs, you may want to use :null_session instead.
	protect_from_forgery with: :exception
	helper_method :current_user
	def current_user
		@current_user ||= User.find(session[:user_id]) if session[:user_id]
		rescue ActiveRecord::RecordNotFound
	end

	def after_sign_in_path_for(resource)
    	candidate_path(:id => current_user.id)
  	end
end

app/controllers/candidates_controller.rb
class CandidatesController < ApplicationController
	def index
	end
    
    def show
    end
    http_basic_authenticate_with :name => "admin", :password => "password1234" 
end

app/controllers/interview_appointments_controller.rb
class InterviewAppointmentsController < ApplicationController
	def new
		@interview_appointment = InterviewAppointment.new
	end

	def create
		@interview_appointment = InterviewAppointment.new(interview_params)
		puts @interview_appointment.inspect
		@interview_appointment.save
		flash[:success] = 'Success!'  
    	redirect_to interview_appointment_path(:id => 1)
	end

	def show
		@interviewer = InterviewAppointment.last

	end

	private

	def interview_params
  		params.require(:interview_appointment).permit(:id, :interviewer, :appointment_date, :appointment_time, :position)
	end
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController   
	def linkedin
		auth = env["omniauth.auth"]
		@user = User.connect_to_linkedin(request.env["omniauth.auth"], current_user)
		if @user.persisted?
			session[:user_id] = @user.id
			flash[:notice] = I18n.t "devise.omniauth_callbacks.success"
			sign_in_and_redirect @user, :event => :authentication
		else
			session["devise.linkedin_uid"] = request.env["omniauth.auth"]
			redirect_to new_user_registration_url
		end
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/candidates_helper.rb
module CandidatesHelper
end

app/helpers/interview_appointments_helper.rb
module InterviewAppointmentsHelper
end

app/helpers/linkedin_helper.rb
module LinkedinHelper
end

app/helpers/omniauth_callbacks_helper.rb
module OmniauthCallbacksHelper
end

app/views/candidates/index.html.erb
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
    <head>
    		<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>CAREERSMOB</title>
        <meta name="description" content="">
			<meta name="viewport" content="width=device-width, initial-scale=1.0"/>
		<link rel="stylesheet" href="assets/basscss.css" rel="stylesheet">
        <link rel="stylesheet" href="assets/main.css" rel="stylesheet">
        <!-- <script src="js/vendor/modernizr-2.6.2.min.js"></script> -->
    </head>
    <body>
        <!--[if lt IE 7]>
            <p class="bclearfixsehappy">You are using an <strong>outdated</strong> bclearfixser. Please <a href="http://bclearfixsehappy.com/">upgrade your bclearfixser</a> to improve your experience.</p>
        <![endif]-->

        <!-- Add your site or application content here -->

<div class="clearfix bg-lighter-gray center">
	<p class="h4 right p3 "><%= link_to "Sign in with LinkedIn", user_omniauth_authorize_path(:linkedin), :class => "blue border p1" %></p>
	<div class="col-4 mx-auto mb4 mt4 p4">
		<span class="h1">CAREERSMOB</span>
	</div>
</div>

<div class="col-6 mx-auto m4 center">
	<span class="h2">Improve your technical	interviewing skill</span>
		<%= link_to user_omniauth_authorize_path(:linkedin), 'data-no-turbolink' => true do %>
            <button class="button-blue-outline mt3 h4">Book free consultation</button>
        <% end %>
</div>

<div class="col-4 mx-auto m4 center border p3">
	<p class="h3">We match you up with the experienced<br> 
	interviewers who have worked<br> 
	at some of the biggest and hottest<br> 
	companies in the valley<br>
	<button class="button-blue-outline mt3 h4">Meet the experts</button>
	</p>

</div>



        <script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
        <script>window.jQuery || document.write('<script src="js/vendor/jquery-1.10.2.min.js"><\/script>')</script>
        <script src="assets/plugins.js"></script>
        <script src="assets/main.js"></script>

        <!-- Google Analytics: change UA-XXXXX-X to be your site's ID. -->
        <script>
            (function(b,o,i,l,e,r){b.GoogleAnalyticsObject=l;b[l]||(b[l]=
            function(){(b[l].q=b[l].q||[]).push(arguments)});b[l].l=+new Date;
            e=o.createElement(i);r=o.getElementsByTagName(i)[0];
            e.src='//www.google-analytics.com/analytics.js';
            r.parentNode.insertBefore(e,r)}(window,document,'script','ga'));
            ga('create','UA-XXXXX-X');ga('send','pageview');
        </script>
    </body>
</html>

app/views/candidates/show.html.erb
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
    <head>
    		<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>Candidate – CAREERSMOB</title>
        <meta name="description" content="">
		<meta name="viewport" content="width=device-width, initial-scale=1.0"/>
		<link rel="stylesheet" href="../assets/basscss.css" rel="stylesheet">
        <link rel="stylesheet" href="../assets/main.css" rel="stylesheet">
        <!-- <script src="js/vendor/modernizr-2.6.2.min.js"></script> -->
    </head>
    <body>
        <!--[if lt IE 7]>
            <p class="bclearfixsehappy">You are using an <strong>outdated</strong> bclearfixser. Please <a href="http://bclearfixsehappy.com/">upgrade your bclearfixser</a> to improve your experience.</p>
        <![endif]-->

        <!-- Add your site or application content here -->


<div class="container p2">
	<div class="clearfix">
		<div class="col col-10 left p1 border">
			 <div class="col col-2 m1 py3 center border bg-lighter-gray rounded">Avatar
					 </div>
					 <div class="col col-8 ml2 py1 bg-lightgray mb3">
					 	
					 		<span class="h2"><%= current_user.first_name %><br> <%= current_user.last_name %></span><br>
					 		<span class="h6"><%= current_user.headline %></span>
					 </div>
					<div class="col col-8 px1 mr1 mb1 justify"><b><%= current_user.summary %>
					</div>
					 <div class="col col-12"><%= link_to "Linkedin", current_user.public_profile_url %>
					 </div>
		</div>
		<div class="col col-2 ">
			<%= link_to('Logout', destroy_user_session_path, :method => :delete, 'data-no-turbolink' => true) %>   
		</div>
	</div>
</div>

<div class="container p2">
	<div class="clearfix">

		<%= link_to new_interview_appointment_path, :class => "col col-2 left border center py3 rounded blue", 'data-no-turbolink' => true do %>				
			<span class="h1 center p1 border circle">
				&nbsp;+&nbsp;</span>
			<span class="col h3 py2 blue">Schedule an interview</span>
			
		<% end %>
		
	</div>
</div>

        <script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
        <script>window.jQuery || document.write('<script src="js/vendor/jquery-1.10.2.min.js"><\/script>')</script>
        <script src="../assets/plugins.js"></script>
        <script src="../assets/main.js"></script>

        <!-- Google Analytics: change UA-XXXXX-X to be your site's ID. -->
        <script>
            (function(b,o,i,l,e,r){b.GoogleAnalyticsObject=l;b[l]||(b[l]=
            function(){(b[l].q=b[l].q||[]).push(arguments)});b[l].l=+new Date;
            e=o.createElement(i);r=o.getElementsByTagName(i)[0];
            e.src='//www.google-analytics.com/analytics.js';
            r.parentNode.insertBefore(e,r)}(window,document,'script','ga'));
            ga('create','UA-XXXXX-X');ga('send','pageview');
        </script>
    </body>
</html>

app/views/interview_appointments/_form.html.erb
<%= form_for(@interview_appointment) do |f| %>
	<div class="container">
		<div class="clearfix center mt4">
			<span class="h1">Schedule an interview</span>
			
			<div class="col-8 mx-auto border mt3">
				<div class="inline-block clearfix mb2">
	 				<div class="col-8 py2 mx-auto">
						<%= f.label :which_position_are_you_interested_in?, :class => "h3" %>
					</div>
					<%= f.text_field :position, :class => "col-12 field-light rounded-right x-group-item center", :placeholder => "Software Engineer" %>
				</div>
			</div>

			<div class="col-8 mx-auto border mt3">
					<div class="col-8 py2 mx-auto">
						<%= f.label :pick_the_date, :class => "h3" %>
					</div>
					<form class="clearfix mb2 px4">
						<%= f.text_field :appointment_date, :class => "col col-6 mb0 field-light rounded-left x-group-item", :placeholder => "Date", :style => "margin-top: -3px" %>
						<%= f.select :appointment_time, options_for_select([["9am", "9am"], ["10am", "10am"], ["11am", "11am"], ["12pm", "12pm"],["1pm", "1pm"], ["2pm", "2pm"], ["3pm", "3pm"], ["4pm", "4pm"], ["5pm", "5pm"], ["6pm", "6pm"], ["7pm", "7pm"]]), :class => "col col-6 mb0 field-light rounded-left x-group-item" %>
					</form>
			</div>

			<div class="col-8 mx-auto border mt3">
				<div class="col-8 py2 mx-auto">
					<%= f.label :select_the_expert, :class => "h3" %>
				</div>
				<div class="clearfix">
					<div class="col col-4">
						<%= f.radio_button :interviewer, "helper1", :value => "HELPER001" %>
						<label for="interviewer">Helper1</label>
					</div>
					<div class="col col-4">
						<%= f.radio_button :interviewer, "helper2", :value => "HELPER002" %>
						<label for="check-helper2">Helper2</label>
					</div>	
					<div class="col col-4">
						
						<%= f.radio_button :interviewer, "helper3", :value => "HELPER003" %>
						<label for="check-helper3">Helper3</label>
					</div>
				</div>
			</div>
			
		<button class="button-red mt3 h2">Submit and schedule</button>
		
	</div>
	
	<script>
		$( document ).ready(function() {
			console.log($("#interview_appointment_appointment_date"));
		  	$("#interview_appointment_appointment_date").datepicker();
		});

		

		// $(".clearfix input").on('change', function() {
		// 	console.log($('input[name="helper-choice"]:checked'));
  //   		alert($('input[name="helper-choice"]:checked', '.clearfix').val());
  //       });
	</script>

<% end %>

app/views/interview_appointments/new.html.erb
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
    <head>
    		<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>CAREERSMOB</title>
        <meta name="description" content="">
			<meta name="viewport" content="width=device-width, initial-scale=1.0"/>
		<link rel="stylesheet" href="../assets/basscss.css" rel="stylesheet">
        <link rel="stylesheet" href="../assets/main.css" rel="stylesheet">
        <link rel="stylesheet" href="//ajax.googleapis.com/ajax/libs/jqueryui/1.11.2/themes/redmond/jquery-ui.css" rel="stylesheet">
    </head>
    <body>
        <!--[if lt IE 7]>
            <p class="bclearfixsehappy">You are using an <strong>outdated</strong> bclearfixser. Please <a href="http://bclearfixsehappy.com/">upgrade your bclearfixser</a> to improve your experience.</p>
        <![endif]-->

        <!-- Add your site or application content here -->


		<%= render 'form' %>


        <script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
        <script src="//ajax.googleapis.com/ajax/libs/jqueryui/1.11.2/jquery-ui.min.js"></script>
        <script>window.jQuery || document.write('<script src="js/vendor/jquery-1.10.2.min.js"><\/script>')</script>
        <script src="../assets/plugins.js"></script>
        <script src="../assets/main.js"></script>

        <!-- Google Analytics: change UA-XXXXX-X to be your site's ID. -->
        <script>
            (function(b,o,i,l,e,r){b.GoogleAnalyticsObject=l;b[l]||(b[l]=
            function(){(b[l].q=b[l].q||[]).push(arguments)});b[l].l=+new Date;
            e=o.createElement(i);r=o.getElementsByTagName(i)[0];
            e.src='//www.google-analytics.com/analytics.js';
            r.parentNode.insertBefore(e,r)}(window,document,'script','ga'));
            ga('create','UA-XXXXX-X');ga('send','pageview');
        </script>
    </body>
</html>

app/views/interview_appointments/show.html.erb
<div class="container p2">
	<div class="clearfix">
		<div class="col col-10 left p1 border">
			 <div class="col col-2 m1 py3 center border bg-lighter-gray rounded">Avatar
					 </div>
					 <div class="col col-8 ml2 py1 bg-lightgray mb3">
					 	
					 		<span class="h2">Congrats! You have an interview scheduled</span><br>
					 		<span class="h6"><%= current_user.headline %></span>
					 </div>
					<div class="col col-8 px1 mr1 mb1 justify"><b>You will have a mock interview with <%= @interviewer.interviewer %></b>
					</div>
					<%= @interviewer.appointment_date %>
					<%= @interviewer.appointment_time.to_s(:time) %> 
				    <g:hangout render="createhangout"
				        invites="[
				                  { id : '<%= current_user.email %>', invite_type: 'EMAIL'}]">
				    </g:hangout>
					
		</div>
	</div>
</div>

<div class="container p2">
	<div class="clearfix">
		<div class="col col-10 left p1 border">
			 <div class="col col-2 m1 py3 center border bg-lighter-gray rounded">Avatar
					 </div>
					 <div class="col col-8 ml2 py1 bg-lightgray mb3">
					 		<span class="h2"><%= current_user.first_name %><br> <%= current_user.last_name %></span><br>
					 		<span class="h6"><%= current_user.headline %></span>
					 </div>
					<div class="col col-8 px1 mr1 mb1 justify"><b><%= current_user.summary %>
					</div>
					 <div class="col col-12"><%= link_to "Linkedin", current_user.public_profile_url %>
					 </div>
		</div>
		
	</div>
</div>
<script src="https://apis.google.com/js/platform.js" async defer></script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Careersmob</title>
  <%= stylesheet_link_tag "http://ajax.googleapis.com/ajax/libs/jqueryui/1.7.2/themes/redmond/jquery-ui.css", "application", media: 'all', 'data-turbolinks-track' => true  %>
  <%= javascript_include_tag "http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js", "http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.1/jquery-ui.min.js", "application", 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>